### PR TITLE
a lot of modifications :)

### PR DESCRIPTION
**Pull request by misterfifi1**

### CODE REVIEW

**Comment by golchha21** [comment]
After going through the pull request I see a lot of unwanted changes have been made hence cannot approve the pull request.

**Comment by misterfifi1** [comment]
Hi,

Could you add comments? That’s an old PR, I don’t remember the context/code
I will have a look.

Thanks

**Comment by golchha21** [comment]
Since it cannot be merged I have take a part of the valid code and added the same to the base.

P.S.:
I am putting up your name in the contributors list.

**Comment by misterfifi1** [comment]
Thanks, do not hesitate to give me more details about the me mission
points, it was very helpful for me, so if it can help other people it will
be good

**Pull request closed without merging**
